# .drone.yml

kind: pipeline
name: default

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  # we don't have tests, awkward
  # - name: test
  #   image: golang:1.17
  #   volumes:
  #     - name: deps
  #       path: /go
  #   commands:
  #     - go test -race -v ./... -cover

  - name: release
    image: golang:1.17
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event:
        - tag

volumes:
  - name: deps
    temp: {}
